__author__ = 'ShortIO Team'
__author_email__ = 'shortio@protonmail.com'
__description__ = 'Short io: must have!'
__license__ = 'MIT'
__title__ = 'shortio'
__url__ = 'https://github.com/byshyk/shortio'
__version__ = '0.0.2'
